// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v3.20.3
// source: slave_bot.proto

package slavebotgrpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Message struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Text string `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
}

func (x *Message) Reset() {
	*x = Message{}
	if protoimpl.UnsafeEnabled {
		mi := &file_slave_bot_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_slave_bot_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_slave_bot_proto_rawDescGZIP(), []int{0}
}

func (x *Message) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

var File_slave_bot_proto protoreflect.FileDescriptor

var file_slave_bot_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x73, 0x6c, 0x61, 0x76, 0x65, 0x5f, 0x62, 0x6f, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x0c, 0x73, 0x6c, 0x61, 0x76, 0x65, 0x62, 0x6f, 0x74, 0x67, 0x72, 0x70, 0x63, 0x22,
	0x1d, 0x0a, 0x07, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x65,
	0x78, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x65, 0x78, 0x74, 0x32, 0x49,
	0x0a, 0x08, 0x53, 0x6c, 0x61, 0x76, 0x65, 0x42, 0x6f, 0x74, 0x12, 0x3d, 0x0a, 0x09, 0x53, 0x74,
	0x61, 0x72, 0x74, 0x43, 0x68, 0x61, 0x74, 0x12, 0x15, 0x2e, 0x73, 0x6c, 0x61, 0x76, 0x65, 0x62,
	0x6f, 0x74, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x1a, 0x15,
	0x2e, 0x73, 0x6c, 0x61, 0x76, 0x65, 0x62, 0x6f, 0x74, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x4d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x28, 0x01, 0x30, 0x01, 0x42, 0x25, 0x5a, 0x23, 0x67, 0x69, 0x74,
	0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x54, 0x65, 0x61, 0x6d, 0x2d, 0x42, 0x61, 0x73,
	0x65, 0x36, 0x34, 0x2f, 0x73, 0x6c, 0x61, 0x76, 0x65, 0x62, 0x6f, 0x74, 0x67, 0x72, 0x70, 0x63,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_slave_bot_proto_rawDescOnce sync.Once
	file_slave_bot_proto_rawDescData = file_slave_bot_proto_rawDesc
)

func file_slave_bot_proto_rawDescGZIP() []byte {
	file_slave_bot_proto_rawDescOnce.Do(func() {
		file_slave_bot_proto_rawDescData = protoimpl.X.CompressGZIP(file_slave_bot_proto_rawDescData)
	})
	return file_slave_bot_proto_rawDescData
}

var file_slave_bot_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_slave_bot_proto_goTypes = []interface{}{
	(*Message)(nil), // 0: slavebotgrpc.Message
}
var file_slave_bot_proto_depIdxs = []int32{
	0, // 0: slavebotgrpc.SlaveBot.StartChat:input_type -> slavebotgrpc.Message
	0, // 1: slavebotgrpc.SlaveBot.StartChat:output_type -> slavebotgrpc.Message
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_slave_bot_proto_init() }
func file_slave_bot_proto_init() {
	if File_slave_bot_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_slave_bot_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Message); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_slave_bot_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_slave_bot_proto_goTypes,
		DependencyIndexes: file_slave_bot_proto_depIdxs,
		MessageInfos:      file_slave_bot_proto_msgTypes,
	}.Build()
	File_slave_bot_proto = out.File
	file_slave_bot_proto_rawDesc = nil
	file_slave_bot_proto_goTypes = nil
	file_slave_bot_proto_depIdxs = nil
}
